list1 = []
fruit1 = input("Enter fruit 1: ")
fruit2 = input("Enter fruit 2: ")
fruit3 = input("Enter fruit 3: ")
fruit4 = input("Enter fruit 4: ")
fruit5 = input("Enter fruit 5: ")
fruit6 = input("Enter fruit 6: ")
fruit7 = input("Enter fruit 7: ")
list1.append(fruit1)
list1.append(fruit2)
list1.append(fruit3)
list1.append(fruit4)
list1.append(fruit5)
list1.append(fruit6)
list1.append(fruit7)
print(list1)

marks = []
mark1 = float(input("Marks 1: "))
mark2 = float(input("Marks 2: "))
mark3 = float(input("Marks 3: "))
mark4 = float(input("Marks 4: "))
marks.append(mark1)
marks.append(mark2)
marks.append(mark3)
marks.append(mark4)
marks.sort()
print(marks)

tuple1 = (5,8,9,4,4,8)
print(tuple1.count(4))

sumList = sum(marks)
print(sumList)
